### ISSUE TITLE
Maximum allowed submissions bugs

### ISSUE THREAD

**Issue by JannisBush** [babe-project/BABE#53]
Specifying `maximum_submissions` for complex experiment has no effect on the activation status of an complex experiment. 
Even if you reach the number of `maximum_submissions`, the experiment stays open. This is not really important, because the number of `maximum_submissions` for a complex experiment is **(variants) * chains * realizations**, but even if this number is reached the experiment does not closes itself and it is the client's responsibility to not submit to that experiment anymore. 
Also, if you specify the `maximum_submissions` for a complex experiment, you can't see the complex information of that experiment anymore, even if you delete `maximum_submissions` again. 

One solution would be to make the fields `maximum_submissions` and `complex_experiment` exclusive.

You can also set the number of `maximum_submissions` to a number lower than the current submissions (which does not really make sense) or to the same number as the current submissions and the experiment does not close itself until the next submission.

**Comment by x-ji** [comment]
Yes, I just didn't take `maximum_submissions` into account because the trituple specification should have been useful enough on its own. I planned to just scrap this column, as Michael also noted that this is not a necessary feature (i.e. if there are extra submissions we can always keep them. No need to deactivate the experiment automatically in any case).

**Comment by x-ji** [comment]
https://github.com/babe-project/BABE/commit/93b805fd31b7d5e9d83eb2736ec5b6668d2b168c
