### ISSUE TITLE
Github Pages deployments of interactive experiments don't seem to be able to connect to the channels

### ISSUE THREAD

**Issue by x-ji** [babe-project/BABE#56]

**Comment by JannisBush** [comment]
The errors on Chrome and Firefox are: 
> phoenix.js:1 WebSocket connection to 'wss://babe-demo.herokuapp.com/socket/websocket?participant_id=18418713194620915258111823817610369118206782272322&experiment_id=58&vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403 

> Firefox can’t establish a connection to the server at wss://babe-demo.herokuapp.com/socket/websocket?participant_id=4fe4f25fc2afd179d1aeb093734ac24fd3d4a266&experiment_id=50&vsn=2.0.0.

I also tried to test other deployment services, e.g. [Zeit Now](https://zeit.co/) and [netlify](https://www.netlify.com/).
- Zeit Now is not working with our current bundling approach, because it just ignore the `node_modules`-folder. We would need to really build our application. Related to https://github.com/babe-project/babe-project/issues/21
- Netlify is working nice. You don't even need to install anything, you can just drag and drop the experiment folder from your computer to their website or connect your github repository. 
The problem is, that the same error as with the GitHub Pages deployment occurs.

**Comment by x-ji** [comment]
What I meant with build scripts is that the script can then run commands after the folder has been uploaded. e.g. if the only folder that's missing is `node_modules`, we can have a build script with the content `npm install`, which would fetch all dependencies into the `node_modules` folder before making the app go live.

Anyways I'll try to fix the connection problem first.

**Comment by x-ji** [comment]
You're right. `check_origin: false` fixed it. Apparently they allow connections from localhost already by default. Nice find. :+1:
